// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDj8w6RYVxKldKCMoTtRDwOdm9fD8dt9c',
    appId: '1:1043442172482:web:a0f765d4989765c6d4a3db',
    messagingSenderId: '1043442172482',
    projectId: 'activity13-2fb56',
    authDomain: 'activity13-2fb56.firebaseapp.com',
    storageBucket: 'activity13-2fb56.firebasestorage.app',
    measurementId: 'G-52QBKLN2XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq8SZxIYAuoxbOJMIAaEdyF4u4IplU6m4',
    appId: '1:1043442172482:android:128b1f7b3c7a078ad4a3db',
    messagingSenderId: '1043442172482',
    projectId: 'activity13-2fb56',
    storageBucket: 'activity13-2fb56.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDj8w6RYVxKldKCMoTtRDwOdm9fD8dt9c',
    appId: '1:1043442172482:web:b7b5f0e1bb250a26d4a3db',
    messagingSenderId: '1043442172482',
    projectId: 'activity13-2fb56',
    authDomain: 'activity13-2fb56.firebaseapp.com',
    storageBucket: 'activity13-2fb56.firebasestorage.app',
    measurementId: 'G-1DVT6WHW5S',
  );
}
